=== Mozu/core-theme/Mozu.SiteBuilder.UX.Themes/Tools/ThemeSettings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" >
  <xs:element name="settings" nillable="true" type="ConfigurationItemCollection" />
  <xs:complexType name="ConfigurationItemCollection">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="items" type="ArrayOfChoice2" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayOfChoice2">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element minOccurs="1" maxOccurs="1" name="item" nillable="true" type="ConfigurationItem" />
      <xs:element minOccurs="1" maxOccurs="1" name="section" nillable="true" type="ConfigurationItemSection" />
      <xs:element minOccurs="1" maxOccurs="1" name="group" nillable="true" type="ConfigurationItemGroup" />
      <xs:element minOccurs="1" maxOccurs="1" name="setting" nillable="true" type="ConfigurationItemField" />
      <xs:element minOccurs="1" maxOccurs="1" name="preset" nillable="true" type="ConfigurationItemPreset" />
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="ConfigurationItem">
    <xs:sequence>
      
      <xs:element minOccurs="0" maxOccurs="1" name="items" type="ArrayOfChoice1" />
      <xs:element minOccurs="0" maxOccurs="1" name="values" type="ArrayOfConfigurationFieldValue" />
      <xs:element minOccurs="0" maxOccurs="1" name="presetValues" type="ArrayOfPresetValue" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="collapsed" type="xs:boolean" />
    <xs:attribute name="visible" type="xs:boolean"  />
    <xs:attribute name="inherit" type="xs:string" />
    <xs:attribute name="type" type="settingType" />
    <xs:attribute name="label" type="xs:string" />
    <xs:attribute name="defaultValue" type="xs:string" />
    <xs:attribute name="presetTriggerGroup" type="xs:string" />
    <xs:attribute name="itemType" type="xs:string" />
    <xs:attribute name="presetTriggerText" type="xs:string" />
  </xs:complexType>
  <xs:simpleType name="settingType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="select"></xs:enumeration>
      <xs:enumeration value="color"></xs:enumeration>
      <xs:enumeration value="font"></xs:enumeration>
      <xs:enumeration value="backgroundImage"></xs:enumeration>
      <xs:enumeration value="radio"></xs:enumeration>
      <xs:enumeration value="checkbox"></xs:enumeration>
      <xs:enumeration value="textbox"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ArrayOfChoice1">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element minOccurs="1" maxOccurs="1" name="section" nillable="true" type="ConfigurationItemSection" />
      <xs:element minOccurs="1" maxOccurs="1" name="group" nillable="true" type="ConfigurationItemGroup" />
      <xs:element minOccurs="1" maxOccurs="1" name="item" nillable="true" type="ConfigurationItem" />
      <xs:element minOccurs="1" maxOccurs="1" name="setting" nillable="true" type="ConfigurationItemField" />
      <xs:element minOccurs="1" maxOccurs="1" name="preset" nillable="true" type="ConfigurationItemPreset" />
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="ConfigurationItemSection">
    <xs:complexContent mixed="false">
      <xs:extension base="ConfigurationItem" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ConfigurationItemGroup">
    <xs:complexContent mixed="false">
      <xs:extension base="ConfigurationItem" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ConfigurationItemField">
    <xs:complexContent mixed="false">
      <xs:extension base="ConfigurationItem" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ConfigurationItemPreset">
    <xs:complexContent mixed="false">
      <xs:extension base="ConfigurationItem" />
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="ArrayOfConfigurationFieldValue">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="option" nillable="true" type="ConfigurationFieldValue" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ConfigurationFieldValue">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="value" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ArrayOfPresetValue">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="item" nillable="true" type="PresetValue" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PresetValue">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="values" type="ArrayOfFieldValue" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="display" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="ArrayOfFieldValue">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="item" nillable="true" type="FieldValue" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FieldValue">
    <xs:attribute name="id" type="xs:string" />
    <xs:attribute name="value" type="xs:string" />
  </xs:complexType>
  <xs:element name="ConfigurationFieldValue" nillable="true" type="ConfigurationFieldValue" />
  <xs:element name="FieldValue" nillable="true" type="FieldValue" />
  <xs:element name="ConfigurationItem" nillable="true" type="ConfigurationItem" />
  <xs:element name="ConfigurationItemGroup" nillable="true" type="ConfigurationItemGroup" />
  <xs:element name="ConfigurationItemField" nillable="true" type="ConfigurationItemField" />
  <xs:element name="ConfigurationItemPreset" nillable="true" type="ConfigurationItemPreset" />
  <xs:element name="ConfigurationItemSection" nillable="true" type="ConfigurationItemSection" />
  <xs:element name="PresetValue" nillable="true" type="PresetValue" />
</xs:schema>

=== Mozu/core-theme/Mozu.SiteBuilder.UX.Themes/Themes/Core3/MetaData/ThemeSettings.xml
<?xml version="1.0"?>
<settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\Tools\ThemeSettings.xsd">
  <items>
    <section id="color" label="Color" visible="true">
      <items>
        <setting id="breadcrumbColor" type="color" label="Breadcrumb Color" defaultValue="#555555"/>
        <setting id="siteBackgroundColor" type="color" label="Site Background" defaultValue="#E5E5E5"/>
        <setting id="wrapBackgroundColor" type="color" label="Container Background" defaultValue="#FFFFFF"/>
        <setting id="contentBackgroundColor" type="color" label="Content Background" defaultValue="#FFFFFF"/>
        <setting id="siteNavColor" type="color" label="Site Navigation Color" defaultValue="#C5C5C5"/>
        <setting id="siteNavHoverColor" type="color" label="Site Navigation Link Hover" defaultValue="#C9C9C9"/>
        <setting id="storeNameColor" type="color" label="Store Name Color" defaultValue="#FEFEFE"/>
        <setting id="textColor" type="color" label="Text Color" defaultValue="#333333"/>
        <setting id="linkColor" type="color" label="Link Color" defaultValue="#4F4F4F"/>
        <setting id="linkVisited" type="color" label="Link Visited Color" defaultValue="#3F3F3F"/>
        <setting id="linkHover" type="color" label="Link Hover Color" defaultValue="#666666"/>
        <setting id="headlineColor" type="color" label="Headline Color" defaultValue="#444444"/>
      </items>
    </section>
    <section id="General" label="General" visible="true">
      <items>
        <setting id="gutterWidth" type="select" label="Gutter Width" defaultValue="20px">
          <values>
            <option value="25px">25px</option>
            <option value="22px">22px</option>
            <option value="20px">20px</option>
            <option value="18px">18px</option>
            <option value="15px">15px</option>
          </values>
        </setting>
        <setting id="defaultPageSize" type="textbox" label="Default Page Size" defaultValue="15"></setting>
      </items>
    </section>
    <section id="font" label="Font" visible="true">
      <items>
        <setting id="siteNavFont" type="font" label="Site Navigation Font" defaultValue="14px Tahoma, sans-serif"/>
        <setting id="storeNameFont" type="font" label="Store Name Font" defaultValue="bold 30px Tahoma, sans-serif"/>
        <setting id="globalFont" type="font" label="Site Font" defaultValue="14px Tahoma, sans-serif"/>
        <setting id="headlineFont" type="font" label="Headline Font" defaultValue="bold 21px Tahoma, sans-serif"/>
      </items>
    </section>
  <section id="js" label="JavaScript" visible="true">
      <items>
          <setting id="useOptimizedJs" type="select" label="Use Optimized JS Files" defaultValue="false">
              <values>
                  <option value="true">Yes</option>
                  <option value="false">No</option>
              </values>
          </setting>
      </items>
  </section>
  </items>
</settings>

=== Mozu/core-theme/Mozu.SiteBuilder.UX.Themes/Themes/Dark/MetaData/ThemeSettings.xml
<?xml version="1.0"?>
<settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\Tools\ThemeSettings.xsd">
  <items>
    <section id="colors" label="Colors" visible="true">
      <items>
        <group id="globalFontColor" label="Global Colors">
          <items>
            <setting id="siteBackgroundColor" type="color" label="Background color behind your site" defaultValue="#E5E5E5"  />
            <setting id="wrapBackgroundColor" type="color" label="Overall background color for your site" defaultValue="#FFFFFF"  />
          </items>
        </group>
        <group id="siteHeaderBackgroundColor" label="Site Header Background Color">
          <items>
            <setting id="siteHeaderBackgroundColor" type="color" label="Background color behind your site header" defaultValue="#333333"  />
            <setting id="wrapBackgroundColor" type="color" label="Overall background color for your site" defaultValue="#FFFFFF"  />
          </items>
        </group>
        <group id="color_nav" label="Navigation">
          <items>
            
            <setting id="navBackgroundColor" type="color" label="Navigation Background Color" defaultValue="#CCCCCC"  />
            <setting id="storeNameColor" type="color" label="Store name color" defaultValue="#FFFFFF"  />
            <setting id="siteNavColorLevel1" type="color" label="Site first level navigation color" defaultValue="#C5C5C5"  />
            <setting id="siteNavVisitedColorLevel1" type="color" label="Site first level navigation visited color" defaultValue="#C5C5C5"  />
            <setting id="siteNavHoverColorLevel1" type="color" label="Site first level navigation hover color" defaultValue="#C5C5C5"  />
            <setting id="siteNavColorLevel2" type="color" label="Site second level navigation color" defaultValue="#333333"  />
            <setting id="siteNavVisitedColorLevel2" type="color" label="Site second level navigation visited color" defaultValue="#FFFFFF"  />
            <setting id="siteNavHoverColorLevel2" type="color" label="Site second level navigation hover color" defaultValue="#FFFFFF"  />
            <setting id="siteNavColorLevel3" type="color" label="Site third level navigation color" defaultValue="#333333"  />
            <setting id="siteNavVisitedColorLevel3" type="color" label="Site third level navigation visited color" defaultValue="#333333"  />
            <setting id="siteNavHoverColorLevel3" type="color" label="Site third level navigation hover color" defaultValue="#00FFFF"  />
          </items>
        </group>
        <group id="color_body" label="Body">
          <items>
            <setting id="contentBackgroundColor" type="color" label="The background color of your content area" defaultValue="#FFFFFF"  />
            <setting id="defaultTextColor" type="color" label="Body text color" defaultValue="#333333"  />
            <setting id="headlineTextColor" type="color" label="Headline color" defaultValue="#666666"  />
            <setting id="subHeadlineTextColor" type="color" label="Sub headline color" defaultValue="#333333"  />
            <setting id="linkColor" type="color" label="Link color" defaultValue="#333333"  />
            <setting id="linkVisited" type="color" label="Link (visited) color" defaultValue="#333333"  />
            <setting id="linkHover" type="color" label="Link (hover) color" defaultValue="#333333"  />
            <setting id="breadcrumbColor" type="color" label="Breadcrumb font color" defaultValue="#555555"  />
          </items>
        </group>
        <group id="color_footer" label="Footer">
          <items>
            <setting id="siteFooterLinkColor" type="color" label="Site footer color" defaultValue="#FFFFFF"  />
            <setting id="siteFooterVisitedLinkColor" type="color" label="Site footer visited color" defaultValue="#FFFFFF"  />
            
            <setting id="siteFooterHoverLinkColor" type="color" label="Site footer hover color" defaultValue="#FFFFFF"  />
          </items>
        </group>
      </items>
      
    </section> 
    <section id="fonts" label="Fonts" visible="true">
      <items>
        <group id="globalFontGroup" label="Global Font">
          <items>
            <setting id="globalFont" type="font" label="Global Font" defaultValue="14px Tahoma, sans-serif"  />
          </items>
        </group>
          <group id="font_site_nav" label="Navigation">
              <items>
                  <setting id="storeNameFont" type="font" label="Store name font" defaultValue="bold 30px Tahoma, sans-serif"  />
                  <setting id="siteNavFontLevel1" type="font" label="Site first level navigation font" defaultValue="14px Tahoma, sans-serif"  />
                  <setting id="siteNavVisitedFontLevel1" type="font" label="Site first level navigation visited font" defaultValue="14px Tahoma, sans-serif"  />
                  <setting id="siteNavHoverFontLevel1" type="font" label="Site first level navigation hover font" defaultValue="14px Tahoma, sans-serif"  />
                  <setting id="siteNavFontLevel2" type="font" label="Site second level navigation font" defaultValue="14px Tahoma, sans-serif"  />
                  <setting id="siteNavVisitedFontLevel2" type="font" label="Site second level navigation visited font" defaultValue="14px Tahoma, sans-serif"  />
                  <setting id="siteNavHoverFontLevel2" type="font" label="Site second level navigation hover font" defaultValue="14px Tahoma, sans-serif"  />
                  <setting id="siteNavFontLevel3" type="font" label="Site third level navigation font" defaultValue="14px Tahoma, sans-serif"  />
                  <setting id="siteNavVisitedFontLevel3" type="font" label="Site third level navigation visited font" defaultValue="14px Tahoma, sans-serif"  />
                  <setting id="siteNavHoverFontLevel3" type="font" label="Site third level navigation hover font" defaultValue="14px Tahoma, sans-serif"  />
              </items>
          </group>
          <group id="content_body" label="Content Body">
          <items>
          </items>
        </group>
        <group id="font_footer" label="Footer">
          <items>
            <setting id="siteFooterLinkFont" type="font" label="Site footer font" defaultValue="11px/110% Tahoma, sans-serif"  />
            <setting id="siteFooterHoverLinkFont" type="font" label="Site footer font (hover)" defaultValue=" 11px/110% Tahoma, sans-serif"  />
          </items>
        </group>
      </items>
    </section>
  </items>
</settings>

=== Mozu/core-theme/Mozu.SiteBuilder.UX.Themes/Themes/Core4/MetaData/ThemeSettings.xml
<?xml version="1.0"?>
<settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\..\..\Tools\ThemeSettings.xsd">
  <items>
    <section id="all" label="All" visible="true">
      <items>
        <setting id="fontFamily" type="textbox" label="Font Family" defaultValue="Rambla, sans-serif" />
        <setting id="fontSize" type="textbox" label="Font Size" defaultValue="14px" />
        <setting id="gutterWidth" type="select" label="Gutter Width" defaultValue="25px">
          <values>
            <option value="25px">25px</option>
            <option value="22px">22px</option>
            <option value="20px">20px</option>
            <option value="18px">18px</option>
            <option value="15px">15px</option>
          </values>
        </setting>
        <setting id="bodyBackgroundColor" type="color" label="Body Background Color" defaultValue="#ffffff" />
      </items>
    </section>
    <!--<section id="color" label="Color" visible="true">
      <items>
        <setting id="breadcrumbColor" type="color" label="Breadcrumb Color" defaultValue="#555555"/>
        <setting id="siteBackgroundColor" type="color" label="Site Background" defaultValue="#E5E5E5"/>
        <setting id="wrapBackgroundColor" type="color" label="Container Background" defaultValue="#FFFFFF"/>
        <setting id="contentBackgroundColor" type="color" label="Content Background" defaultValue="#FFFFFF"/>
        <setting id="siteNavColor" type="color" label="Site Navigation Color" defaultValue="#C5C5C5"/>
        <setting id="siteNavHoverColor" type="color" label="Site Navigation Link Hover" defaultValue="#C9C9C9"/>
        <setting id="storeNameColor" type="color" label="Store Name Color" defaultValue="#FEFEFE"/>
        <setting id="textColor" type="color" label="Text Color" defaultValue="#333333"/>
        <setting id="linkColor" type="color" label="Link Color" defaultValue="#4F4F4F"/>
        <setting id="linkVisited" type="color" label="Link Visited Color" defaultValue="#3F3F3F"/>
        <setting id="linkHover" type="color" label="Link Hover Color" defaultValue="#666666"/>
        <setting id="headlineColor" type="color" label="Headline Color" defaultValue="#444444"/>
      </items>
    </section>
    <section id="General" label="General" visible="true">
      <items>
        <setting id="gutterWidth" type="select" label="Gutter Width" defaultValue="20px">
          <values>
            <option value="25px">25px</option>
            <option value="22px">22px</option>
            <option value="20px">20px</option>
            <option value="18px">18px</option>
            <option value="15px">15px</option>
          </values>
        </setting>
        <setting id="defaultPageSize" type="textbox" label="Default Page Size" defaultValue="15"></setting>
      </items>
    </section>
    <section id="font" label="Font" visible="true">
      <items>
        <setting id="siteNavFont" type="font" label="Site Navigation Font" defaultValue="14px Tahoma, sans-serif"/>
        <setting id="storeNameFont" type="font" label="Store Name Font" defaultValue="bold 30px Tahoma, sans-serif"/>
        <setting id="globalFont" type="font" label="Site Font" defaultValue="14px Tahoma, sans-serif"/>
        <setting id="headlineFont" type="font" label="Headline Font" defaultValue="bold 21px Tahoma, sans-serif"/>
      </items>
    </section>
  <section id="js" label="JavaScript" visible="true">
      <items>
          <setting id="useOptimizedJs" type="select" label="Use Optimized JS Files" defaultValue="false">
              <values>
                  <option value="true">Yes</option>
                  <option value="false">No</option>
              </values>
          </setting>
      </items>
  </section>-->
  </items>
</settings>
